---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include_tasks: jenkins_pre.yml
- include_tasks: jenkins_install.yml

- block: # Config Jenkins
  - include_tasks: jenkins_post.yml
  tags:
    - jenkins-config
